### ISSUE TITLE
Do you plan to package it?

### ISSUE THREAD

**Issue by tiotrom** [linuxmint/webapp-manager#1]
AUR, Flatpak, Appimage? :) - I am closely keeping an eye on this and I was wondering if you plan to package it. Thanks!

**Comment by clefebvre** [comment]
Not yet. It comes with very relaxed dependencies and doesn't really care what versions of these you're running, so for now anyway it should run in any distro and any release.

We recently made a flatpak for warpinator and we're looking into making an AppImage as well, but the situation is different there. Warpinator requires modern python modules and libs which aren't available in many distributions. That problem doesn't exist with webapp-manager.

That said, if there's anything preventing you from running it in your environment, please let us know so we can fix it.
