### ISSUE TITLE
How can I build this software

### ISSUE THREAD

**Issue by CleanMachine1** [linuxmint/webapp-manager#102]
I am trying to build from source however I always get dependency errors and compilation errors.

How can I compile from source?

**Comment by hsbasu** [comment]
This app is based on python. So you don't need to build it. There are two ways you can install/use it:
**Option 1:** Copy the contents of `etc` and `usr` to `/etc/` and `/usr/` respectively. And run `webapp-manager` from terminal or use the .desktop.
**Option 2:** Download the [*.deb](https://github.com/hsbasu/webapp-manager/releases/download/1.0.9/webapp-manager_1.0.9_all.deb) file from my fork. **Caution:** there might be **untested** features.

**Comment by Zahrun** [comment]
@hsbasu, please add python3-pil to the list of dependencies
