### ISSUE TITLE
[Suggestion] Category of webapp-manager

### ISSUE THREAD

**Issue by hsbasu** [linuxmint/webapp-manager#112]
At present the default category of `webapp-manager` is **Internet**. However, by nature the `webapp-manager` is an **Accessory** or **Utility** which creates new **applications** meant for accessing different web-based products. So, the default category of `webapp-manager` should be either **Accessory** or **Utility**

**Comment by clefebvre** [comment]
Yes, that's arguable. I don't agree it would be better in Accessories but you do make a valid point. I'll close this issue since it's subjective.
