### ISSUE TITLE
Firefox Nightly is not being recognised

### ISSUE THREAD

**Issue by Magolor44** [linuxmint/webapp-manager#125]
The only browsers that are being recognised by the webapp-manager are (for me) Firefox and Falkon. This is a problem, because I only use base-Firefox if Nightly breaks so addons like NoScript aren't properly configured on that browser which can break websites. I would be really happy if there would be some way to recognise Nightly and maybe other unrecognised browsers (if any) so this won't be a problem in the future.

**Comment by hsbasu** [comment]
`webapp-manager` does not support **Firefox Nightly** till `1.1.5`. If you want I can create a PR to support Nightly. Until then you can add the following line in `usr/lib/webapp-manager/common.py` after **line 134**
```
browsers.append(Browser(BROWSER_TYPE_FIREFOX, "Firefox Nightly", "??", "/usr/bin/??"))
```
I don't know the command for NIghtly. Please replace `??` with the executable command for Nightly.

**Comment by Magolor44** [comment]
Thanks! The command for nightly is `nightly`, btw.
