### ISSUE TITLE
Brave browser not found error

### ISSUE THREAD

**Issue by jversusk** [linuxmint/webapp-manager#13]
I'm able to add a Brave browser entry in the main window, but it doesn't appear in the system menu and clicking the Launch button gives a `brave not found` error. I'm guessing the `exec` value in this line should be `brave-browser` and not just `brave`:
https://github.com/linuxmint/webapp-manager/blob/85b5872da9149cbf48d91799d8575fac6af06e88/usr/lib/webapp-manager/common.py#L120

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/webapp-manager/commit/db2af59cae0da924faaacf5e9f4113ff05b0f5fd
