### ISSUE TITLE
Maximise, minimise, and close buttons not visible

### ISSUE THREAD

**Issue by Netherquark** [linuxmint/webapp-manager#132]
OS: Linux
Distro: Manjaro Rolling
DE: GNOME 40
Theme: Qogir-Dark
Webapp Manager: 1.1.5+1+g2f3e132

The 3 icons are not visible in Web Apps. Excuse the Youtube recommendations, but this is what it looks like:
![image](https://user-images.githubusercontent.com/65618735/130979947-27e97570-2600-4002-aaf3-ffd898190a88.png)

Compared to that, this is how other applications look like:
![image](https://user-images.githubusercontent.com/65618735/130980581-8c82b244-274e-41f3-ba5e-eac2ae2dafbc.png)

**Comment by Mek101** [comment]
I think it would be a better idea to check whatever the DE is gnome and then then act on that instead of adding a new option

**Comment by murtezayesil** [comment]
Client side decoration in Firefox integrates window control buttons into tab bar which is part of the navigation bar. A toggle to enable or disable title bar can be added which would toggle the client side decorations.

In case you are wondering where is the client side decoration toggle in Firefox, it is the "title bar" check mark at the bottom left of UI customization screen 

# Suggestion
Add a check box asking user whether to hide tittle and window controls when "hide navigation bar" is checked.
