### ISSUE TITLE
Firefox entensions cannot be added due to notification pop-up not shown

### ISSUE THREAD

**Issue by prog-amateur2** [linuxmint/webapp-manager#145]
Hello, I am on webapp-manager version `1.1.5` and Firefox `94`. 

When I try to install web extension in Firefox (following the `README` instructions), I click install then the loading animation takes forever to install the web app. 

This is due to the fact that, normally, I should click on a notification pop-up to allow permission to install the web extension, however this notification pop-up does not appear on the screen when I use webapp-manager. 

Could you please tell me if version `1.1.6` does fix this issue, or in the case it doesn't fix it, could you please check this problem ? 

Thank you very much for your kind help.

**Comment by hsbasu** [comment]
> When I try to install web extension in Firefox (following the `README` instructions), I click install then the loading animation takes forever to install the web app.

Which method did you use?
 
> This is due to the fact that, normally, I should click on a notification pop-up to allow permission to install the web extension, however this notification pop-up does not appear on the screen when I use webapp-manager.

Have you turned on the `Navigation bar`?

**Comment by prog-amateur2** [comment]
> Which method did you use?

Thank you for your help. Please find below the procedure I follow : 
1. Open a web-app
2. Click on `Alt`
3. Select `Bookmarks > Addons`
4. Fill the field with `ublock origin` (for instance)
5. Click on `Add to Firefox`
6. Admire the infinite loop (this is where the notification pop-up for permission shall appear)

> Have you turned on the `Navigation bar`?

No, I didn't. Please find the result of my test : 
1. With `Navigation bar` turned on the pop-up appears and I can install the extension
2.  With `Navigation bar` turned off the pop-up does not appears and I can't install the extension

However, before version `1.1.5`, I could install Addons extensions without any issue. As of today, I still can install addons with web-apps that have been made before version `1.1.5`, so to me, I don't think it is a missing feature, but more like a broken feature. 

Thank you for your feedback.

**Comment by bkmo** [comment]
This issue affects me too. Is it possible to turn on navbar after creating the webapp? Addons can only be installed if the navbar is enabled.

**Comment by kaboom36** [comment]
I was able to work around this issue by editing the profiles userchrome.css changing `visibility: collapse` to `visibility: shown` so the navbar is enabled, installing the extension, and changing visibility back to collapse
