### ISSUE TITLE
Using the Flatpak Version of Chromium

### ISSUE THREAD

**Issue by Grant12311** [linuxmint/webapp-manager#156]
Hello. I recently switched from Chrome to Chromium for privacy reasons. This transition largely went very smoothly except for the fact that I cannot use the flatpak version of Chromium with this web app manager. The snap version of Chromium gave me issues with hardware acceleration (I also just don't care for snaps), so I use the flatpak version. But it isn't recognized by this program as an available browser like Firefox, Chrome. and the Chromium snap are. Is there some kind of workaround for this, or would a patch be necessary?

**Comment by Grant12311** [comment]
After doing some digging, this seems like a pretty easy thing for me to just add in myself. I'm going to have a go at it later today. I assume it would be a welcome pull request?

**Comment by Grant12311** [comment]
Ah, it turns out this is already implemented, just not in the package I have from the Linux Mint repo. My apologizes.

**Comment by musiclover382** [comment]
I think this was closed in #78
