### ISSUE TITLE
Suggestion - Title bar

### ISSUE THREAD

**Issue by dipenSan** [linuxmint/webapp-manager#16]
Hello, LM team. First thank you for making this useful app.
If I set browser : Firefox. Then it show the title bar of window "Facebook - Firefox"
But if I set browser : chrome. Now it only show "Facebook" as a window title which is good. It looks that I'm really using standalone app. Can you please remove extra title "Firefox".
Thank you.

**Comment by clefebvre** [comment]
That's not up to us unfortunately, that's how Firefox works. Afaik it's not configurable so we can't set it that way.

**Comment by LinuxOnTheDesktop** [comment]
Can the manager launch the 'app' without a titlebar at all? Chrome's inbuilt 'appify'-type feature offers the user the option of doing that.

**Comment by beevabeeva** [comment]
Check the script in this answer: https://askubuntu.com/a/721132

It works like a charm!
Just make sure you use the long dash for Firefox.
My rule in ~/window_names.txt to remove the `— Mozilla Firefox` suffix is simply:
```
firefox// — Mozilla Firefox//
```
You will know what I'm talking about after you read through the post (read the entire thread).

Hope that helps

**Comment by captn3m0** [comment]
There's a issue on Bugzilla for the same: https://bugzilla.mozilla.org/show_bug.cgi?id=1667664
