### ISSUE TITLE
Question (Bug?) - Size and position of "Web App" is not saved or reused

### ISSUE THREAD

**Issue by mbedded** [linuxmint/webapp-manager#163]
Hello together,

i upgraded my tools by using "apt" as usual.
Since 1-2 weeks I have the issue that the window size and position of a web-app is not remembered anymore.

Any website i added as app is opened full height with 50% screen width.
![image](https://user-images.githubusercontent.com/22235508/158069721-01d8da50-a4b2-4cd2-8f48-8518334481d9.png)

Some windows where located on a second screen and always started with their "old" position and size as i closed them.
Nowadays everything is opened "half screen" (as shown in the screenshot and i have to resize and move all windows every time by hand.

Is this a "bug" or can i change the behavior somewhere by configuration?
Maybe this is chrome-related but it is difficult for me the see the cause. As said: Some weeks ago everything worked fine and this bug may be a co-incidence.
The "chrome browser" (separate) remembers its position and size.

My specs:
```
OS - Linux Mint 20.3
Chromium - Version 99.0.4844.51 (Official Build) for Linux Mint (64-bit)
Web Apps - Version 1.1.9
```

Thank you very much

Best regards
Matthias

**Comment by erteacher** [comment]
Hello there!
It's happening the same to me too.
At first Web Apps was running OK, but suddenly something went wrong with the window's size, it doesn't keep its size after closing.
**My specs:
OS - Linux Mint 20.3
Microsoft Edge - Version 99.0.1150.38 (Official build) (64-bit)
Web Apps - Version 1.1.9**

**Comment by mchilli** [comment]
Hey hey,
I think its a problem with chromium itself. Since version 99.0.4844.0 it has this weird behaviour.
It was also reported as a bug [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1302381&q=%22window%20size%22&can=1) and as it said in the latest post the "--app" argument is not supported anymore.
I think we have to use another browser from now on.

**Comment by mbedded** [comment]
@mchilli thank you for your link. I'll close my ticket now because it's chrome related.
I tried webapps-manager with different Browsers (e.g. Vivaldi and Firefox) and the window position was saved and restored as before.

Thank you for your help. I hope this issue helps other users, too :)

**Comment by asbleal** [comment]
for a workaround look here: 
https://forums.linuxmint.com/viewtopic.php?t=369706

hope this helps :)

**Comment by mbedded** [comment]
It's a nice idea. Thank you very much :)
I would start the application by CLI then but thats okay

**Comment by SmoochySix4** [comment]
If you are using Chrome, you could just set the parameters for the windows size in the custom parameters section with `--window-size=1920,1080`

**Comment by stefan-jevtic** [comment]
Also, you can use the `--window-position=x,y` flag
