### ISSUE TITLE
How allow notifications ( push ) in Firefox webapp ?

### ISSUE THREAD

**Issue by Coeur-Noir** [linuxmint/webapp-manager#168]
Hi,

may sound silly, but without address bar, how allow a Firefox based webapp to show notifications ?

Is there a way to temporarily show the address bar ?
Or another way to add a website as allowed for notifications « afterwards » ?

**Comment by mtwebster** [comment]
You can hit the 'alt' key to temporarily show the menubar....from there you can also go to Tools->Page Info, and adjust permissions.

Is this what you're after?

**Comment by Coeur-Noir** [comment]
I knew the Alt key.

But for allowing site notifications in Firefox, one needs to first confirm it through a pop-up originating from an icon inside the url / address bar.

Once this ↑ done, you can modify permissions for that site inside the Tools → Page Info.

But as long as you don't confirm your choice in the afore mentioned pop-up, you won't be able to modify permissions ( or add that site to the list, there's no add option there, only modify or delete ).

![Peek 12-04-2022 03-09](https://user-images.githubusercontent.com/1895947/162858476-3fa35af7-0615-446c-9f4e-3155ca610144.gif)

![Peek 12-04-2022 03-12](https://user-images.githubusercontent.com/1895947/162858959-ef1dca7c-3b47-4376-992b-832e37c8cb66.gif)

**Comment by jaysonwcs** [comment]
You can display the address bar changing the name of the file userChrome.css to something like userChrome.css.old . This is the file that determines the modified appearance of Firefox. It's located inside the chrome folder, which is inside the profile folder of your webapp. Then, you open your webapp again and the bar will be there.
After finishing the change, you change the name of userChrome.css.old back to userChrome.css.

**Comment by koelle25** [comment]
> You can hit the 'alt' key to temporarily show the menubar....from there you can also go to Tools->Page Info, and adjust permissions.
> 
> Is this what you're after?

As I stood before the same problem I just recorded a quick video showing how to do that (so future me and other people can see it, too):

https://user-images.githubusercontent.com/915514/218044825-9eee5a31-019b-40bd-8c57-4aaeb49972ce.mp4

**Note:** You can also just press CTRL+I to open the page info/permissions popup.
