### ISSUE TITLE
Feature Request: Open Links in External Browser

### ISSUE THREAD

**Issue by svidovich** [linuxmint/webapp-manager#181]
I would really like a setting where I can make all links I click in the web app open in an external browser. I specifically use this thing for Google Messages, and every time I click a link in a message and it kills my messenger window, my heart cries into the void.

Thank you...!

**Comment by hsbasu** [comment]
Isn't it a option for you to select open in new window from the right click menu?

**Comment by svidovich** [comment]
:facepalm: yes lmao. Look what I've become. The worst end user possible

Thank you c:
