### ISSUE TITLE
Desktop file doesn't appear in KDE

### ISSUE THREAD

**Issue by chase9** [linuxmint/webapp-manager#184]
I'm wondering what is the purpose of this line when generating .desktop files for webapp-manager:

https://github.com/linuxmint/webapp-manager/blob/5c1ecbbc941b7b744f2a6c750831e5dfd87bb63d/generate_desktop_files#L22

I can confirm that webapp-manager successfully launcher from KDE's kickoff.

**Comment by bkmo** [comment]
Desktop files are generated for KDE with OnlyShowIn=KDE;
The other NotShownIn=KDE is included in the .desktop files created for other DE's

**Comment by chase9** [comment]
Thank you for pointing that out!
