### ISSUE TITLE
Issue adding custom icon -- stuck at "loading"

### ISSUE THREAD

**Issue by tansowny-tech** [linuxmint/webapp-manager#187]
When I install webapp-manager from the AUR on Arch Linux I cannot manually select an icon for a web app from a custom folder. When I browse and select the icon I just get a loading message and the icon is never available. I have tried it on multiple installs, multiple desktop environments (Plasma, MATE, and Xfce) and even multiple distros (Arch Linux and EndeavourOS) and the same behaviour happens on each.

![Peek 2022-07-14 12-07](https://user-images.githubusercontent.com/67082788/179052449-5d2a9569-cc68-43f0-a786-073052976240.gif)

**Comment by bkmo** [comment]
Same as OP on arch

**Comment by mtwebster** [comment]
fixed:

https://github.com/linuxmint/xapp/commit/6fa9ca993482e57e550243a815ade449cf790665
