### ISSUE TITLE
Add Feature: Minimize App to Tray Icon

### ISSUE THREAD

**Issue by WHOmagoo** [linuxmint/webapp-manager#19]
Add a feature that allows minimization of a web page to the tray so the page is still loaded and running but just not it task bar.

**Comment by clefebvre** [comment]
Sorry that's beyond the scope for now. We just configure and launch browser, we don't embed them into a wrapper application.

**Comment by akmalkady** [comment]
I would love to have this feature as well. After @clefebvre  reply. I tried to find a solution and I found:
KDocker (http://kdocker.sourceforge.net/) 
KDocker will help you dock any application into the system tray.

**Comment by Moini** [comment]
Agreed, this would probably be the only feature that would make the webapps more useful to me than attached tabs in Firefox.

**Comment by seityaya** [comment]
I want to bring this topic up again. 
I think this is already within the scope of the application implementation. And improved usability. The next step will be the ability to minimize the application to tray when closed. For example, make a separate checkmark for this when setting up.
