### ISSUE TITLE
Ip address not supported in "address" field

### ISSUE THREAD

**Issue by MauroFoti** [linuxmint/webapp-manager#2]
I was trying to create a web app for some internal website I'm using and, if in the "address" field I put `192.168.1.1`, the button "ok" is greyed out; the same happens with `http://192.168.1.1` and `http://192.168.1.1/`. I guess that it is only configured for hostnames. I'm using 1.0.3, the `.deb` that was just released on linux mint dev news

**Comment by BerndJM** [comment]
After I noticed that in my case the IP for "localhost" at 192.168.178.200 works fine, I played a bit with the address field.
It looks like there is a too rudimentary plausibility check: "must have a dot must have at least two characters after the dot":
192.168.178.1 - didn't work
192.168.178.10 - works
192.168.17.10 - didn't work
192.1 - didn't work
192.16 - works
192.168 - works
Even if some of this examples didn't make sense ;-) it explains why my IP works and @MauroFoti s IP didn't work.
I think this check should be reworked - also it would be nice if "localhost" could be recogniced ...

**Comment by muzena** [comment]
It doesn't work for me either.
I tried IP for [Tvheadend](https://github.com/tvheadend/tvheadend) server
http://localhost:9981
or
http://192.168.0.11:9981

**Comment by MauroFoti** [comment]
@BerndJM  It looks like you are right. Indeed, here are some tests:
aaa.aa :heavy_check_mark:
aa.aaa :x:
a.aaa.aa :heavy_check_mark:
a.a.aaa.aa :heavy_check_mark:
.aaa.aa:9 :heavy_check_mark:
.aaa.aa:944444 :heavy_check_mark:
a.aa.aa :x:
.aaa.a :x:
The rule seems to be:

> There must be a dot, the tld should be two or more characters, the domain name should be three or more characters

subsequent subdomains are ignored. As far as I know this does not even cover every possible domain name, as two-characters domain names are allowed.

**Comment by jmoorewv** [comment]
My temporary solution to this issue was to rewrite the 'get_url' function within the webapp-manager.py file to check if the URL is a valid IP address or not. If the URL is a valid IP address than it would append 'http://' if it wasn't included in the URL. If the URL is not an IP address than it would continue the valid domain check.

```
    # Reads what's in the URL entry and returns a validated version
    def get_url(self):
        import re
        url = self.url_entry.get_text()
        if re.findall(r"\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b", url):
            if not "://" in url:
                url = "http://%s" % url
            return url
        else:
            if not "://" in url:
                url = "http://%s" % url
            (scheme, netloc, path, _, _, _) = urllib.parse.urlparse(url, "http")
            if "." not in netloc:
                return ""
            components = netloc.split(".")
            if len(components[-1]) < 2:
                return ""
            if len(components[-2]) < 3:
                return ""
            return url
```

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/webapp-manager/commit/5a571d5f5fd36aabeeec06b1c341cd56462907fa
