### ISSUE TITLE
Small issue when unmaximize the web app window (chrome related)  

### ISSUE THREAD

**Issue by gadass** [linuxmint/webapp-manager#20]
I would like to report a small problem with web apps using chrome. 

Steps to reproduce:

1. Run the app and maximize
2. Close the app
3. Run again
4. Drag or unmaximize the window 

In the fourth step, instead of restoring it to normal size, reduces to an invisible size. This is not a problem using the firefox browser to create the web app.

**Comment by clefebvre** [comment]
This looks like an upstream issue with Chrome, we can't fix it at our level afaik.
