### ISSUE TITLE
Missing Browser Engine

### ISSUE THREAD

**Issue by Bahesh** [linuxmint/webapp-manager#214]
Hi ,When i used it first , it was working perfectly fine , it had all the browser engines, but then i installed another OS , and then back to the same OS , after that brave browser is not being shown up , i use brave for numerous websites (for privacy) and then now its missing. tried reinstalling it , waited . It didnt work so i decided to report this.

**Comment by NA0341** [comment]
@Bahesh Troubleshoot **first** *before* reporting!

**How to, you ask?**

For all software that abides by the [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard), there's standardized locations for Application Data. For the data stored per user there are the following options:

+ `~/.appname` (hidden subfolder, can contain any application-related data)
+ `~/.local/share/appname` (hidden subfolder, can contain any application-related data)
+ `~/.config/appname` (hidden subfolder, contains config files - as the name suggests)
+ `~/.cache/appname` (hidden subfolder, contains cache files - as the name suggests)

Some Software also creates "normal" (not hidden) folders in the users home directory or it's (unhidden) subdirectories. Those shouldn't contain any configuration or cache files.

**Tip:** Hidden Folders can be shown using `CTRL + H` shortcut in almost any file explorer.

**Note:** Most (electron) WebApps violate this standard by storing all their data in `~/.config/appname`. If an application cannot separate it's data files it should use one of the first two options.

In most cases, an Application not opening is either

+ bad configuration
+ missing librarys
+ or (in some cases) issues with the system configuration.


**Steps to troubleshoot:**

1. Run in Terminal to check program output.
*Depending on the output, continue with the one of the following steps:*

+ Install missing librarys.
+ Remove App Data.
+ Investigate & Change System Config OR Create Workaround.

**How-To: Remove App Data**

Delete or rename the applications data folders.
For example, you could rename `.appname` to `appname` or `appname.bak` (file ending that indicates a backup(-file)).


Why am I writing all this?
Simple! To have a template that I can reuse whenever I want. And you could learn something :)
