### ISSUE TITLE
Export-Import option

### ISSUE THREAD

**Issue by blaineclrk** [linuxmint/webapp-manager#22]
It would be great to have an Export-Import option, or else Backup-Restore. Either would do.
This is better than having browser bookmarks that have to be sync'd across browsers, specially when there are browsers that don't have sync. Plus I can open a page for use in teleconferencing share and not have the clutter of the nav bar.

**Comment by clefebvre** [comment]
This is all saved in ~/.local/share/applications. Backing that up is enough to restore it elsewhere.

**Comment by blaineclrk** [comment]
TY

**Comment by OatmanGeorge** [comment]
Sorry, to comment on a closed issue, but I see the .desktop files in ~/.local/share/applications, how do you also backup/restore the saved profiles, logins, add-ons and such set for each saved web app? Would it be the ~/.local/share/ice files, or would I need something else too? Thank you.

**Comment by 0HAg0** [comment]
> This is all saved in ~/.local/share/applications. Backing that up is enough to restore it elsewhere.

If you are content with a default profile created by webapp-manager, that will be sufficient. But you you have to activated the profiles in webapp-manager to make it work.

If you want to backup and restore icons and profiles, you supposedly have to copy and restore  ~/.local/share/ice as well - but so far I haven't been able to make it work. So how do you do that? Customizing an profile can be very time consuming, and so is doing it again, on another computer. Been able to backup and restore everything, is therefore very needed.
