### ISSUE TITLE
Feature Request:  Suport for launching in Default Firefox profile using Tab Containers

### ISSUE THREAD

**Issue by ZebulonGlitch** [linuxmint/webapp-manager#229]
I just tried the web-app tool out (v1.2.5 via Mint 21 repos) and it's really cool!  

But... dealing with a virgin firefox for every web-app is kind of an overly tedious deal breaker...  Could you please support launching web-apps in our default firefox profile in specified containers?

Containers are a game changer for browsing - and I rely on them to segregate any group of sites that share a common SSO in a common sphere of my life.  Trusted sites that I want to sign me in and recognize me - on my terms when I want.  (I otherwise browse outside of tab containers where cookies are always deleted aggressively thanks to a firefox plugin called "Cookie Autodelete" which is container aware - one can set container specific cookie retention rules.

I hope it's clear how incredibly nice this setup is for using the internet.  Lets us have our cake and eat it too.  I'm never tracked, yet I still have full convenience of easy sign-ins by just opening up one of the services I use in the appropriate Tab Containers where my login session cookies have been white-listed to evade deletion.  Ba-da-boom.

- With WebApps as it now stands, I need to go hack on all of the objectionable firefox settings, add addins, and do an SSO signin - for every single web-app I set up.  Tedious and hard to maintain.
- If we could use our main firefox profile, and instead specify what container to use, we'd still enjoy the same privacy and cookie segregation, but we'd be able to set one SSO authentication token in that container and let multiple web-apps share.  Also, no firefox customizations would be needed, because the plugins and features we like would already be in place.

It's like firefox tab containers and your web-apps were born for each other.  :)  Hope my pitch made some sense!

**Comment by soo-shan** [comment]
Maybe not exactly what you may be looking but Simple Tab Groups extension support containers.

**Comment by ZebulonGlitch** [comment]
For info, i've been using the web-app tool a lot, and have more experience with it now.  I actually think the way it works is quite good - it creates new profiles for every web-app so that they're isolated from each other and from my main firefox instance.

I'm gonna mark this closed / cancelled because the containers feature in Firefox doesn't need to be considered - mixing the two would now with hindsight, likely be overcomplicated.  aka, a bad idea.  Let containers do its job in the main firefox instance.  Let Webapps be isolated little worlds with their own cookies and settings.  :)
