### ISSUE TITLE
Webapps (in firefox) not honoring not to show Title bar after relauch

### ISSUE THREAD

**Issue by soo-shan** [linuxmint/webapp-manager#234]
Hello,

I unchecked title bar for firefox using customize toolbar option but it shows again for web app after reopening the webapp.
The setting is working fine for firefox as a browser.

I'm on fedora 37 gnome edition

workaround: [link](https://github.com/linuxmint/webapp-manager/issues/304#issue-2342687676)

Images for reference 
![image](https://user-images.githubusercontent.com/39080326/219934129-aadc67ed-f8c0-42af-a56e-e872734e848e.png)

![image](https://user-images.githubusercontent.com/39080326/219934108-4105a612-6f66-4462-9ded-8375222c7479.png)

![image](https://user-images.githubusercontent.com/39080326/219940473-9e5df63e-a526-442f-8784-26cd92dd0735.png)

**Comment by PioApocalypse** [comment]
Same problem on LM 21.2 Cinnamon, it seems like deactivating the title bar is the only non-persistent change too: i.e. if I choose for example to always hide the bookmarks toolbar or disable javascript directly from the about:config tab in FF the change is persistent after restarting the web app, while if I uncheck the title bar option or manually deactivate the title bar from the about:config tab the change is reverted upon restarting.

**Comment by soo-shan** [comment]
workaround: [link](https://github.com/linuxmint/webapp-manager/issues/304#issue-2342687676)
