### ISSUE TITLE
I can't enable desktop notifications in webapps using firefox engine

### ISSUE THREAD

**Issue by felipetac** [linuxmint/webapp-manager#235]
I create any webapp using the firefox engine but when I enable the desktop notifications the confirmation pop-up keeps blinking indefinitely, not allowing me to click on the button to authorize.

Versions:

> Linux Mint 21.1 Cinnamon
> Cinnamon 5.6.7
> Kernel Linux 5.15.0-60-generic
> webapp-manager 1.2.8
> firefox 110.0+linuxmint1+vera

Image:
![Captura de tela de 2023-02-20 19-16-31](https://user-images.githubusercontent.com/2755031/220207040-b70cae4a-0d35-4941-a84c-1911b1b90aab.png)

**Comment by SyluxS7** [comment]
Same problem as above with Kubuntu

**Comment by SyluxS7** [comment]
Same with Kubuntu

Operating System: Kubuntu 22.10
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.6
Kernel Version: 5.19.0-31-generic (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 2700 Eight-Core Processor
Memory: 62.8 Gio of RAM
Graphics Processor: NVIDIA GeForce RTX 2060/PCIe/SSE2
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7B84
System Version: 2.0

**Comment by murkl** [comment]
same here

**Comment by jberlyn** [comment]
A workaround I have found for this is to enable the Navigation Bar in edit screen of the specific web app. Once you've enabled notifications or whatever things you need, you can disable the Navigation Bar again and go back to using it like normal.
