### ISSUE TITLE
No supported browsers were detected.

### ISSUE THREAD

**Issue by hazzery** [linuxmint/webapp-manager#247]
Upon running `webapp-manager`, "No supported browsers were detected." is printed to console and the gui opens fine but I am unable to click the plus button as apparently I have no web browsers. I am running Ubuntu 22.04.2 and definitely have both Firefox and Brave installed

**Comment by haggen88** [comment]
@hazzery In what format are they installed? [deb, snap, flatpak]

**Comment by hazzery** [comment]
@haggen88 Firefox came preinstalled with Ubuntu so I assume snap but am not sure, I don't know how I can check. I installed Brave from the Ubuntu Software store / snap store app, which uses snap.

**Comment by hazzery** [comment]
Whoops that was an accident

**Comment by haggen88** [comment]
@hazzery  Running 'snap list' you can see the apps installed in snap format, to see the apps in flatpak format you must execute 'flatpak list'. At the moment the only browser in snap format supported in webapp-manager is Chromium.

**Comment by hazzery** [comment]
@haggen88 Ahh I see that would explain the problem, they are indeed both installed with snap. Are there plans for further support for snap?

**Comment by haggen88** [comment]
I have no idea. LM is not as close to Snap  [although you could ask them to add Firefox as snap for example]. Here you can see the currently [supported browsers](https://github.com/linuxmint/webapp-manager/blob/master/usr/lib/webapp-manager/common.py#L174).

**Comment by Nitrousoxide** [comment]
I am also getting this error, despite brave and firefox being installed via flatpak.

```
📦[Brian@fedora ~]$ webapp-manager
📦[Brian@fedora ~]$ No supported browsers were detected.
^C
📦[Brian@fedora ~]$ flatpak list | grep "brave"
Brave Browser	com.brave.Browser	1.60.125	stable	flathub	system
📦[Brian@fedora ~]$ ^C
📦[Brian@fedora ~]$ flatpak list | grep "firefox"
Firefox	org.mozilla.firefox	120.0.1	stable	flathub	system
📦[Brian@fedora ~]$ flatpak run org.mozilla.firefox
Gtk-Message: 19:48:00.455: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:48:00.455: Failed to load module "pk-gtk-module"
Gtk-Message: 19:48:00.456: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:48:00.456: Failed to load module "pk-gtk-module"
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
[Parent 2, Main Thread] WARNING: Failed to call GetIdletime(): GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
: 'glib warning', file /builds/worker/checkouts/gecko/toolkit/xre/nsSigHandlers.cpp:187

** (firefox:2): WARNING **: 19:48:05.803: Failed to call GetIdletime(): GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

^C📦[Brian@fedora ~]$ 

```

Mind you this in inside of a distrobox container, but they are both visible to a flatpak list command and I can successfully start up the application by doing the flatpak run command within the distrobox.

These are the distrobox commands I used to set it up.  It worked long enough to setup a single PWA using firefox but then it seems to have broken.

**Comment by Turtle6665** [comment]
I **almost** found a workaround to the problem with snapped Firefox. Currently, I can lunch the app when using the File Manager and accessing `menu://applications/webapps-webapps` or adding the app to the desktop. 

1. Allow webapp manager to find snapped Firefox by faking a normal Firefox installation using Symlinks.

```
sudo ln -s /home/$USER/snap/firefox/common/.mozilla/firefox/ /usr/bin
```

2. Allow snapped Firefox to use webapp manager created profiles ([as snap doesn't allow editing files outside the `/home`](https://askubuntu.com/a/1033617))

  - 2.1. Create an empty folder witch will contain the created Firefox profiles. For clearness, the file is named `webapp-manager-profiles` but will have to be renamed in step 2.3

```
mkdir /home/$USER/snap/firefox/common/.mozilla/firefox/webapp-manager-profiles
```

  - 2.2. Create a symlink where webapp manager will put the created profiles

```
ln -s /home/$USER/snap/firefox/common/.mozilla/firefox/webapp-manager-profiles /home/$USER/.local/share/ice
```
  - 2.3. Rename this file to match what expect webapp manager

```
mv /home/$USER/.local/share/ice/webapp-manager-profiles /home/$USER/.local/share/ice/firefox
```

3. Use webapp manager to create your webapps desktop app

**Comment by hsbasu** [comment]
Added PR #291 to support Firefox snap packaging. Now pure Ubuntu users can also use Ubuntu's default installed Firefox.

**Comment by yllekz** [comment]
Recently I've run into an issue where Web Apps won't detect all flatpaks. It sees LibreWolf on my system but not Ungoogled Chromium.
