### ISSUE TITLE
Suggestion: Clear cookies/cache button

### ISSUE THREAD

**Issue by BCoder626** [linuxmint/webapp-manager#25]
I have a suggestion for this project. I think there should be a "reset" button somewhere in the edit menu for a web app to clear all the cookies and stored login info. That way, you don't have to remove the app and re-add it to achieve this.

**Comment by shadowstreik** [comment]
Seconded

**Comment by clefebvre** [comment]
You can do this already, press Alt -> Edit -> Preferences.
