### ISSUE TITLE
Desktop file not shown in KDE's kickoff

### ISSUE THREAD

**Issue by hazel-bunny** [linuxmint/webapp-manager#253]
Hi, I'm packaging this app for Fedora [here](https://github.com/hazel-bunny/webapp-manager-fedora). Prebuilt binaries are downloadable from [my copr](https://copr.fedorainfracloud.io/coprs/hazel-bunny/ports). The RPM builds successfully but the app isn't shown on kickoff. @PizzaLovingNerd 's [fork](https://github.com/risiIndustries/webapp-manager) does show up however.

Reproducible on Fedora 37, 38 and Rawhide.

**Comment by mtwebster** [comment]
You need to install the kde desktop file:
https://github.com/risiIndustries/webapp-manager/blob/1869d34b0959a2d183193d878fff7259b11fdee7/webapp-manager.spec#L48
