### ISSUE TITLE
Squashed toggle button

### ISSUE THREAD

**Issue by schance995** [linuxmint/webapp-manager#27]
Using the Flat Remix GTK theme and I get this:
![wide button from theme](https://user-images.githubusercontent.com/54919210/94853496-7b947900-03f9-11eb-9bf3-d1b032a7b806.png)
![toggle on](https://user-images.githubusercontent.com/54919210/94853815-f067b300-03f9-11eb-8765-d57346e3d692.png)

I'm not sure if this is a theme specific issue, but toggle buttons in other apps with the same theme do not look like this.

**Comment by LazyyCoder** [comment]
Same here in Yaru theme
