### ISSUE TITLE
Thin gray border at the top on Firefox

### ISSUE THREAD

**Issue by victorbnl** [linuxmint/webapp-manager#279]
There is an unexpected 1px gray border at the top when using Firefox.

![image](https://github.com/linuxmint/webapp-manager/assets/39555268/2fa95fda-d0f0-4701-8571-2866955bb3dc)

This seems to be the bottom border of the menu bar, but it shouldn’t be there when the menu bar is hidden.

![image](https://github.com/linuxmint/webapp-manager/assets/39555268/fb754d97-16bf-4ef8-8a77-ac4b3f9db3a0)

Note that there isn’t on Chrome:

![image](https://github.com/linuxmint/webapp-manager/assets/39555268/8a272535-0d48-4a81-b546-edb8d64f6458)

**Comment by MeatImp** [comment]
reviewed pull request and seems fine to me!
