### ISSUE TITLE
Ability to set a fixed value for dimension of window

### ISSUE THREAD

**Issue by mriza** [linuxmint/webapp-manager#285]
Hi. Is it possible to set a fixed value for window dimension and/or disable scrollbar? My use case is I want to view a web app that only has less than 500x500 px and I dont want to open the web app in full screen size. Thank you.

**Comment by MeatImp** [comment]
According to [this superuser post](https://superuser.com/questions/629844/how-can-i-launch-web-browser-automatically-with-given-window-size-and-url)

you can add these parameters on the "custom parameters" tab when editing your webapp settings

`-height 500 -width 500 "example.com"`

if this fixes your issue be sure to mark it as closed.

**Comment by mriza** [comment]
thank you
