### ISSUE TITLE
Core dump upon instantiating the program

### ISSUE THREAD

**Issue by Tejaromalius** [linuxmint/webapp-manager#289]
**Steps to reproduce**
1. Run a fresh instance of webapp-manager after reboot through gnome app menu
---
Details:
[reports.zip](https://github.com/linuxmint/webapp-manager/files/14730843/reports.zip)

**Comment by hsbasu** [comment]
Check out this solution from [StackOverflow](https://stackoverflow.com/questions/42279510/couldnt-find-foreign-struct-converter-for-cairo-context).
