### ISSUE TITLE
Support for Chromium-based browsers

### ISSUE THREAD

**Issue by shadowstreik** [linuxmint/webapp-manager#29]
Please build necessary modules to operate Chromium-based browsers and their additional themes & extensions.

**Comment by tiotrom** [comment]
I was wondering about that too. I hope it will be integrated ;).

**Comment by BetaMaxHeadroom** [comment]
The webapp-manager seems to work well in my cinnamon flavored ubuntu install. But, I recently spilled water on that laptop. So, that's out of the picture for now. I'm using Kali 20.04 on a really old laptop, and it only identifies firefox for some reason. I assume that this is a permissions issue. Does anyone happen to know how to work through this? If so, please let me know.

**Comment by clefebvre** [comment]
Most Chromium based browsers are supported.

Extensions and plugins that's another topic but we'll need more precise issues for this.
