### ISSUE TITLE
Custom browser support

### ISSUE THREAD

**Issue by Octelly** [linuxmint/webapp-manager#315]
This would enable support for more browsers. I could imagine this working like this:
- users sets path to browser
- sets path to browser data (for profile stuff if necessary)
- chooses between Chromium, Firefox or (maybe?) custom (custom would probably warrant a "may not work well" warning if even feasible)
- optional browser-specific arguments, overrides, etc.

Personally, I just want to be able to use [Floorp](https://github.com/Floorp-Projects/Floorp/), but noticed there's already quite a few requests for other browsers: #276, #197, #140, #158 and perhaps others (didn't check too thoroughly).

**Comment by melroy89** [comment]
I'm also using Floorp. I removed Firefox. And now my webapps aren't working. 

Not only that.. I can't easily switch the browser settings in the WebApp manager!

**Comment by melroy89** [comment]
OK, Let me try to add Floorp via a Pull Request myself.

**Comment by melroy89** [comment]
PR created for Floorp: https://github.com/linuxmint/webapp-manager/pull/316
