### ISSUE TITLE
[Feature request] Add checksum (ex : SHA)

### ISSUE THREAD

**Issue by prog-amateur2** [linuxmint/webapp-manager#32]
Hello I hope you won't hate me, it's me again for a request that I consider very important. 

Unless I didn't get a good look (and forgive me if I was wrong then), [your server unfortunately doesn't offer checksum verification](https://linuxmint.com/tmp/blog/3969/). 

![2020-10-20_14-33](https://user-images.githubusercontent.com/60101083/96586879-1da8d200-12d1-11eb-9752-07eaa1a17423.png)

The risk is real, especially since [it has already happened to Linux Mint ISO in 2016](https://blog.linuxmint.com/?p=2994), so it should not be taken lightly and above all it should not happen again. 

Rather than asking you to add development work when you already have a lot of it, I was thinking of simply populating a small file like the one on the [debian repository](https://cdimage.debian.org/mirror/cdimage/archive/9.9.0/amd64/iso-cd/) like in this example. 

![2020-10-20_14-34](https://user-images.githubusercontent.com/60101083/96586889-213c5900-12d1-11eb-8038-423f431c0c8c.png)

A "text" file (at least with SHA256 for example) takes very little time to fill and it greatly improves security. What do you think about it? 

Thank you !

**Comment by clefebvre** [comment]
I agree. This is just an alpha build we gave like that just as a preview, not a repository.. but yeah, in principle I do agree.
