### ISSUE TITLE
Using Opera browser (chromium based)

### ISSUE THREAD

**Issue by burhanuday** [linuxmint/webapp-manager#35]
There is no option to use Opera browser.

Fix -
add an entry to https://github.com/linuxmint/webapp-manager/blob/85b5872da9149cbf48d91799d8575fac6af06e88/usr/lib/webapp-manager/common.py#L115

I can take this issue up

**Comment by burhanuday** [comment]
adding this should do the trick:
```
 browsers.append(Browser(BROWSER_TYPE_CHROMIUM, "Opera", "opera", "/usr/bin/opera"))
```

**Comment by burhanuday** [comment]
This does not work as intended. It opens a new window but takes the user to the new tab page

**Comment by clefebvre** [comment]
Yes, Opera needs to add support for kiosk mode or isolated profiles. I'll close this since there's nothing we can do on our side.
