### ISSUE TITLE
Entries extending .desktop format should start with X-

### ISSUE THREAD

**Issue by cdfa** [linuxmint/webapp-manager#37]
The .desktop files that are created for Firefox have an entry `IceFirefox=GoogleDrive7775`.
However, this is not according to the .desktop spec:
```
$ desktop-file-validate webapp-GoogleDrive7775.desktop
webapp-GoogleDrive7775.desktop: error: file contains key "IceFirefox" in group "Desktop Entry", but keys extending the format should start with "X-"
```

**Comment by clefebvre** [comment]
ICE made files this way and we didn't change it to keep fully compatible with it. We can consider changing though. I'm not sure what this key is for.. I'll have to check before.
