### ISSUE TITLE
Can not Choose Linux Mint Chromium as Browser 

### ISSUE THREAD

**Issue by joshontech** [linuxmint/webapp-manager#39]
I have installed the 1.0.3 version of web apps manager and it will not allow me to select chromium as the base browser for my youtube web app. 

OS Version - Linux Mint 20
Kernel - 5.4.0-58
Chromium - 87.0.4280.88
Laptop - Dell XPS 13 P54G

**Comment by clefebvre** [comment]
Can you run `apt content chromium | grep bin`?

**Comment by joshontech** [comment]
This is what I get.

joshontech@joshontech-XPS:~$ apt content chromium | grep bin
/usr/bin
/usr/bin/chromedriver
/usr/bin/chromium
/usr/lib/chromium/snapshot_blob.bin
/usr/lib/chromium/v8_context_snapshot.bin

**Comment by joshontech** [comment]
Also I have been trying out mint 20.1 beta and the version of web apps on that is working with chromium.

**Comment by clefebvre** [comment]
I'll close, I can't reproduce. I must assume you had an old version at the time.

**Comment by joshontech** [comment]
> I'll close, I can't reproduce. I must assume you had an old version at the time.

Yes it has since been fixed I am sorry I didn't let you know sooner. Thanks again for an amazing application!
