### ISSUE TITLE
The manager does not offer all my browsers

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/webapp-manager#50]
I have

- Firefox
- Firefox ESR
- Chrome
- Iridium

I want to use Firefox ESR for Netflix (because my main Firefox is set to use a VPN and a proxy, and Netflix rejects those). At present I have a script that disables my VPN and runs a 'Chrome App' that actually uses Iridium. I had hoped that your Webapps would allow me to use Firefox ESR instead. But under 'browsers' Webapp offers, only: 'Firefox'; 'Chrome'. EDIT: screenshot now added: 
![image](https://user-images.githubusercontent.com/47056543/104132945-72139900-5378-11eb-800b-2bfa7069425d.png)

Mint 20.1.

**Comment by Coeur-Noir** [comment]
( try a fullscreen screenshot with few seconds delay ? )

**Comment by ugly95** [comment]
Hypnotix supports Vivaldi (stable branch).  But Vivaldi has a snapshot branch as well.  If a user has vivaldi-snapshot installed, it is not listed in the dropdown menu.

If installed the snapshot branch of Vivaldi can be launched with vivaldi-snapshot

I would appreciate if there was support for vivaldi-snapshot as well.

**Comment by clefebvre** [comment]
Hi,

Please create one issue per missing browser. When you do, we need the following information:

- where did you get the browser from?
- what is the absolute path to its binary?
