### ISSUE TITLE
Unable to add .co. in (FQDN / Address)

### ISSUE THREAD

**Issue by kilo2011** [linuxmint/webapp-manager#52]
When entering the address of the site, the OK button becomes greyed out when entering co.za for example. In other words, soon as the second dot is added, the OK button becomes grey. (Linux Mint 20.1,Cinnamon, Webapps 1.0.3)

![Screenshot from 2021-01-10 23-11-45](https://user-images.githubusercontent.com/6833297/104135450-3ccb7300-5399-11eb-9226-cf26b0975601.png)

**Comment by clefebvre** [comment]
This was fixed already. Not reproducible in 1.1.0.
