### ISSUE TITLE
Installation on Debian 10 (buster) Xfce

### ISSUE THREAD

**Issue by Angedestenebres** [linuxmint/webapp-manager#69]
Hello,

I tried to install this application for test purposes on Debian 10. The installation was a success but I got a first error (see screen below) when I started it. After investigation, I noticed that the package `python3-pillow` was necessary but after the installation of this package I got a new error:

![Debian-starting-error-WebappManager](https://user-images.githubusercontent.com/21110485/104846927-6cb8d000-58dd-11eb-8fdb-77603cb881fc.png)

I think this is related to python3 but I don't know the right package to install.

Do you have an idea?

Thanks in advance.

Ps : On Linux Mint it works well and I think this is a good think to have a software like that! Thanks to the team :wink:

**Comment by ardelsaut** [comment]
Hi, I'm on debian bueleyess testing and I had that problem 
`Traceback (most recent call last):
  File "/usr/lib/webapp-manager/webapp-manager.py", line 20, in <module>
    from common import _async, idle, WebAppManager, Browser, download_favicon, ICONS_DIR, BROWSER_TYPE_FIREFOX
  File "/usr/lib/webapp-manager/common.py", line 243, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
`

After installing python3-pillow from testing debian repos, all is working well!
Ty the devs!

**Comment by mtwebster** [comment]
@Angedestenebres, unfortunately Xapps 1.4 is required and Debian Buster (10) only has 1.2 currently.

The packaging has been updated to reflect this:
https://github.com/linuxmint/webapp-manager/commit/7bee6f353a0ad79d08553c72fde2af03cfa5da7e
