### ISSUE TITLE
Request for support of different webbrowser profiles (firefox)

### ISSUE THREAD

**Issue by userBart** [linuxmint/webapp-manager#7]
Hello,

right now there is no option to select a profile. This is often useful if using different web-browser profiles on one computer/login (e.g. using two profiles for two users sharing one desktop-login at home, having two firefox icons like "firefox -p user1" and "firefox -p user2" or using different profiles to separate sessions, bookmarks and cookies).

Therefore I ask for an option to select a profile. Using firefox this means something like "firefox -p profilename". Maybe also an option is to evoke the profile-manager itself via "firefox -profilemanager".

Thanks!

**Comment by clefebvre** [comment]
We can only run Firefox with isolated profiles, as opposed to existing ones. We need a dedicated profile to be able to mimick a kiosk mode (simplified window with no navbar).

**Comment by userBart** [comment]
This is a pity, but probably cannot be changed as described.

Unfortunately, this means that there is a usability fallstrike, e.g. if you open your webmailer as a WebApp and click on a link (in a mail) that takes you to another page (e.g. from a newsletter to a seller's offer). As you are not in your usual webbrowser profile, the stored credentials/login data (and maybe special browser extensions) are missing...

In this case Web-Apps should only be used in isolated settings like online-banking but not in settings with link-opportunities outside the defined WebApp-domain-url, right?

Thanks

**Comment by clefebvre** [comment]
This can be done with Chromium afaik. If you install chromium, it will appear as an option in webapp-manager and you can then select the web-app to not be isolated.

**Comment by userBart** [comment]
Thanks for this hint - yes this does work using Chromium (just tested).
 ("Unfortunately" I'll use firefox extensively)
