### ISSUE TITLE
Add a Confirm dialogue before app removal

### ISSUE THREAD

**Issue by PeterDaveHello** [linuxmint/webapp-manager#75]
This Web App manger is pretty awesome, maybe a confirm dialogue can make it even better.

I have some tweaks(browser based) on a certain web app, but when I try to add another web app in the manager ... I clicked the wrong button 😅 ... then all tweaks are gone 😱 

That's my fault, but would really appreciate if we can have a confirm button before really delete it 😄 

Thanks a lot!

**Comment by hsbasu** [comment]
Possible Duplicate #66

**Comment by hsbasu** [comment]
I shall try to create a PR on this.

**Comment by PeterDaveHello** [comment]
Thanks @hsbasu

**Comment by hsbasu** [comment]
You are most welcome.
