### ISSUE TITLE
Is it possible to access add-on menu without Firefox navigation bar enabled

### ISSUE THREAD

**Issue by PeterDaveHello** [linuxmint/webapp-manager#77]
Some extensions need its menu to configure, the preference page of extension is not enough, especially for the site specified configs.

**Comment by shom13** [comment]
Exactly, i am stuck with the same problem as i havent enabled navigation bar while creating the webapp. Wondering is there any way of adding the navigation bar after having created the app

**Comment by miloskroulik** [comment]
This looks like a duplicate of https://github.com/linuxmint/webapp-manager/issues/64.

**Comment by PeterDaveHello** [comment]
Looks so, unless there're other solutions. Let's close this one and move to $64.
