### ISSUE TITLE
Request a category for Web apps

### ISSUE THREAD

**Issue by Cloweling** [linuxmint/webapp-manager#8]
The application is currently in beta, but I don't know if you have planned to add a new category in the UI, to give the user the opportunity to have the Web apps in a category.

At the moment the categories that are seen are the following: internet, accessories, games, graphics, office, video & sound and programming, if one were added with the name Web Apps it would be great.

Thanks for your work, this new application is very useful.

**Comment by clefebvre** [comment]
Done.
