### ISSUE TITLE
Wrong capitalisation on .desktop file name preventing correct icons on Wayland

### ISSUE THREAD

**Issue by spoorun** [linuxmint/webapp-manager#82]
In Wayland, for icons and window management (including pinning apps to the task manager in KDE) require the app_id to match exactly the .desktop file name.

 the **app_id** created by webapp-manager is something like: 
 WebApp-GoogleDrive3731
 (from the desktop file: e.g. Exec=google-chrome --app=https://drive.google.com/ --class=WebApp-GoogleDrive3717 --user-data-dir=/home/bursek/.local/share/ice/profiles/GoogleDrive3717

But webapp-manager names the desktop file: webapp-GoogleDrive3717.desktop
Note the lowercase letters. It should be WebApp-GoogleDrive3717.desktop

This happens with every app created by webapp-manager.

I am running Manjaro Linux with KDE and Wayland. Due to the above error, webapp-manager apps do not the display the correct icons. When I manually rename the .desktop file with the correctly-capitalised name, the apps work perfectly.

Thanks

**Comment by spoorun** [comment]
This seems a very trivial issue, but the fix would seem simple -  with lots of of distros moving to Wayland in the coming months, and Chromium and Electron becoming Wayland native this issue will become more pertinent.

**Comment by spoorun** [comment]
Any news on this?

**Comment by OnePinkSheep** [comment]
I can confirm this happens to me, too. I'm on Fedora 36 Gnome, and while on Wayland, I'm just getting a generic icon rather than the app icon. When on a Xorg session, the icons are correct.

**Comment by spoorun** [comment]
This would seem a very simple issue to fix... I'll try but it's not in my area of competence.
If anyone is game that would be great, it now has added importance since KDE is about to default to Wayland. :s
