### ISSUE TITLE
.

### ISSUE THREAD

**Issue by shivanshsinghx365** [linuxmint/webapp-manager#86]

**Comment by RadRussianRus** [comment]
Noticed it too with ScrollAnywhere. I've disabled scrollbar in its settings, but it hides only after refreshing a page. Looks like for some reason Firefox gives site higher priority than extensions when loading, but for some reason it happens only in WebApp mode.

**Comment by RadRussianRus** [comment]
Looks like I've found a problem. WebApp Manager uses `--class <customClass>` option. If you remove it from command in start menu entry, it will properly load extensions before loading page, like it should.
